// <auto-generated />
using System;
using EnterpriseIDS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseIDS.Infrastructure.Migrations
{
    [DbContext(typeof(EnterpriseIdentityDbContext))]
    [Migration("20250817160013_InitialJwtTokenSystem")]
    partial class InitialJwtTokenSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFromLdap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemGroup")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLdapSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapDistinguishedName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapSecurityIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapSyncHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.HasIndex("TenantId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.GroupRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InheritToChildGroups")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MappingConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingSource")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("GroupRoleMappings");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.JwtToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("接收者 (aud claim)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasComment("客戶端 ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("建立時間");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasComment("刪除時間");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasComment("Token 過期時間");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasComment("是否已刪除");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT")
                        .HasComment("Token 發行時間");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("發行者 (iss claim)");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("JWT ID (jti claim)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最後使用時間");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasComment("額外的 Metadata (JSON 格式)");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("TEXT")
                        .HasComment("父級 Token ID");

                    b.Property<Guid?>("RefreshTokenId")
                        .HasColumnType("TEXT")
                        .HasComment("關聯的 Refresh Token ID");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasComment("撤銷時間");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("TEXT")
                        .HasComment("撤銷者使用者 ID");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("撤銷原因");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Scopes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasComment("授權範圍 (space-separated)");

                    b.Property<string>("SourceIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasComment("來源 IP 地址");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasComment("Token 狀態");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("主體 (sub claim)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT")
                        .HasComment("租戶 ID");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("Token 類型 (access_token, refresh_token, id_token)");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasComment("Token 值 (已加密或雜湊)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("更新時間");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasComment("使用次數");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("User Agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasComment("使用者 ID");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_JwtTokens_ExpiresAt")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IssuedAt")
                        .HasDatabaseName("IX_JwtTokens_IssuedAt");

                    b.HasIndex("JwtId")
                        .IsUnique()
                        .HasDatabaseName("IX_JwtTokens_JwtId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("ParentTokenId")
                        .HasDatabaseName("IX_JwtTokens_ParentTokenId")
                        .HasFilter("[ParentTokenId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("RefreshTokenId")
                        .HasDatabaseName("IX_JwtTokens_RefreshTokenId")
                        .HasFilter("[RefreshTokenId] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_JwtTokens_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_JwtTokens_UserId");

                    b.HasIndex("TenantId", "TokenType")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TokenType", "Status")
                        .HasDatabaseName("IX_JwtTokens_TokenType_Status");

                    b.HasIndex("TenantId", "TokenType", "ExpiresAt")
                        .HasDatabaseName("IX_JwtTokens_TenantId_TokenType_ExpiresAt");

                    b.HasIndex("TenantId", "UserId", "Status")
                        .HasDatabaseName("IX_JwtTokens_TenantId_UserId_Status");

                    b.HasIndex("UserId", "TokenType", "Status")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("JwtTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_JwtTokens_ExpiresAt", "[ExpiresAt] > [IssuedAt]");

                            t.HasCheckConstraint("CK_JwtTokens_Status", "[Status] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_JwtTokens_TokenType", "[TokenType] IN ('access_token', 'refresh_token', 'id_token')");

                            t.HasCheckConstraint("CK_JwtTokens_UseCount", "[UseCount] >= 0");
                        });
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.LdapConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalAttributeMapping")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthenticationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictResolution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableIncrementalSync")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstNameAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupBaseDn")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupMemberAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupNameAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupSearchFilter")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreSslErrors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastNameAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConnections")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNestingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SearchTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAccountDn")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAccountPassword")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SyncDisabledUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncFrequencyMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncGroups")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncNestedGroups")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatistics")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseStartTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserBaseDn")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserSearchFilter")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameAttribute")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("LdapConfigurations");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefaultRole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionConditions")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionScope")
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDomainsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AllowedDomains");

                    b.Property<string>("BrandingJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Branding");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedById")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledFeaturesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EnabledFeatures");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("en-US");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryDomain")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotasJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Quotas");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SecuritySettingsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SecuritySettings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenantType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Tenant_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tenant_IsDeleted");

                    b.HasIndex("ParentTenantId")
                        .HasDatabaseName("IX_Tenants_ParentTenantId")
                        .HasFilter("[ParentTenantId] IS NOT NULL");

                    b.HasIndex("PrimaryDomain")
                        .HasDatabaseName("IX_Tenants_PrimaryDomain")
                        .HasFilter("[PrimaryDomain] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_Slug")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Tenants_Status");

                    b.HasIndex("TenantType")
                        .HasDatabaseName("IX_Tenants_TenantType");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("IX_Tenants_Status_IsDeleted");

                    b.ToTable("Tenants", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tenants_Email_Format", "[ContactEmail] IS NULL OR [ContactEmail] LIKE '%@%.%'");

                            t.HasCheckConstraint("CK_Tenants_Slug_Format", "[Slug] NOT LIKE '%[^a-z0-9-]%' AND [Slug] NOT LIKE '-%' AND [Slug] NOT LIKE '%-'");
                        });
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.TenantConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AllowedValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("string");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInheritable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_TenantConfigurations_Category")
                        .HasFilter("[Category] IS NOT NULL");

                    b.HasIndex("ConfigKey")
                        .HasDatabaseName("IX_TenantConfigurations_ConfigKey");

                    b.HasIndex("ConfigType")
                        .HasDatabaseName("IX_TenantConfigurations_ConfigType");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_TenantConfiguration_CreatedAt");

                    b.HasIndex("IsRequired")
                        .HasDatabaseName("IX_TenantConfigurations_IsRequired")
                        .HasFilter("[IsRequired] = 1");

                    b.HasIndex("EffectiveDate", "ExpiryDate")
                        .HasDatabaseName("IX_TenantConfigurations_EffectiveDate_ExpiryDate")
                        .HasFilter("[EffectiveDate] IS NOT NULL OR [ExpiryDate] IS NOT NULL");

                    b.HasIndex("TenantId", "Category")
                        .HasDatabaseName("IX_TenantConfigurations_TenantId_Category")
                        .HasFilter("[Category] IS NOT NULL");

                    b.HasIndex("TenantId", "ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantConfigurations_TenantId_ConfigKey");

                    b.ToTable("TenantConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_TenantConfigurations_ConfigKey_Format", "[ConfigKey] NOT LIKE '% %' AND [ConfigKey] NOT LIKE '%[^a-zA-Z0-9._-]%'");

                            t.HasCheckConstraint("CK_TenantConfigurations_ConfigType_Valid", "[ConfigType] IN ('string', 'int', 'long', 'double', 'decimal', 'bool', 'datetime', 'json')");

                            t.HasCheckConstraint("CK_TenantConfigurations_EffectiveDate_BeforeExpiry", "[EffectiveDate] IS NULL OR [ExpiryDate] IS NULL OR [EffectiveDate] < [ExpiryDate]");

                            t.HasCheckConstraint("CK_TenantConfigurations_SortOrder_NonNegative", "[SortOrder] >= 0");

                            t.HasCheckConstraint("CK_TenantConfigurations_Version_Positive", "[Version] > 0");

                            t.Property("Tags")
                                .HasColumnName("Tags1");
                        });
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.TokenBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BlacklistExpiresAt")
                        .HasColumnType("TEXT")
                        .HasComment("黑名單到期時間 (null 表示永久)");

                    b.Property<DateTime>("BlacklistedAt")
                        .HasColumnType("TEXT")
                        .HasComment("加入黑名單的時間");

                    b.Property<Guid?>("BlacklistedByUserId")
                        .HasColumnType("TEXT")
                        .HasComment("加入黑名單的使用者 ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("建立時間");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasComment("刪除時間");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasComment("是否已刪除");

                    b.Property<bool>("IsPermanent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasComment("是否為永久黑名單");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("JWT ID (jti claim)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasComment("額外的 Metadata (JSON 格式)");

                    b.Property<DateTime>("OriginalExpiresAt")
                        .HasColumnType("TEXT")
                        .HasComment("Token 原本的過期時間");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasComment("加入黑名單的原因");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT")
                        .HasComment("租戶 ID");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("Token 雜湊值 (用於快速比對)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasComment("Token 類型");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasComment("黑名單類型");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("更新時間");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasComment("使用者 ID");

                    b.HasKey("Id");

                    b.HasIndex("BlacklistExpiresAt")
                        .HasDatabaseName("IX_TokenBlacklists_BlacklistExpiresAt")
                        .HasFilter("[BlacklistExpiresAt] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("BlacklistedAt")
                        .HasDatabaseName("IX_TokenBlacklists_BlacklistedAt");

                    b.HasIndex("BlacklistedByUserId");

                    b.HasIndex("JwtId")
                        .IsUnique()
                        .HasDatabaseName("IX_TokenBlacklists_JwtId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("OriginalExpiresAt")
                        .HasDatabaseName("IX_TokenBlacklists_OriginalExpiresAt")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TokenBlacklists_TenantId");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_TokenBlacklists_TokenHash")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_TokenBlacklists_Type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TokenBlacklists_UserId");

                    b.HasIndex("IsPermanent", "BlacklistExpiresAt")
                        .HasDatabaseName("IX_TokenBlacklists_IsPermanent_BlacklistExpiresAt");

                    b.HasIndex("TenantId", "JwtId")
                        .HasDatabaseName("IX_TokenBlacklists_TenantId_JwtId");

                    b.HasIndex("TenantId", "TokenHash")
                        .HasDatabaseName("IX_TokenBlacklists_TenantId_TokenHash");

                    b.HasIndex("UserId", "Type")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("OriginalExpiresAt", "BlacklistExpiresAt", "IsPermanent")
                        .HasDatabaseName("IX_TokenBlacklists_Cleanup");

                    b.HasIndex("TenantId", "UserId", "Type")
                        .HasDatabaseName("IX_TokenBlacklists_TenantId_UserId_Type");

                    b.ToTable("TokenBlacklists", null, t =>
                        {
                            t.HasCheckConstraint("CK_TokenBlacklists_BlacklistExpiry", "([IsPermanent] = 1 AND [BlacklistExpiresAt] IS NULL) OR ([IsPermanent] = 0)");

                            t.HasCheckConstraint("CK_TokenBlacklists_BlacklistedAt", "[BlacklistedAt] <= [OriginalExpiresAt]");

                            t.HasCheckConstraint("CK_TokenBlacklists_TokenType", "[TokenType] IN ('access_token', 'refresh_token', 'id_token')");

                            t.HasCheckConstraint("CK_TokenBlacklists_Type", "[Type] IN (1, 2, 3, 4, 5, 6, 7, 8)");
                        });
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFromLdap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLdapSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapDistinguishedName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapObjectGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapSecurityIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LdapSyncHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordLastChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.UserGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGroupAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SourceType")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroupMemberships");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("SourceGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Group", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Group", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId");

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.GroupRoleMapping", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Group", "Group")
                        .WithMany("RoleMappings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.Role", "Role")
                        .WithMany("GroupMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.JwtToken", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.JwtToken", "ParentToken")
                        .WithMany("ChildTokens")
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnterpriseIDS.Core.Entities.JwtToken", "RefreshToken")
                        .WithMany()
                        .HasForeignKey("RefreshTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnterpriseIDS.Core.Entities.User", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentToken");

                    b.Navigation("RefreshToken");

                    b.Navigation("RevokedByUser");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.LdapConfiguration", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Role", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Tenant", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "ParentTenant")
                        .WithMany("ChildTenants")
                        .HasForeignKey("ParentTenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.TenantConfiguration", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Configurations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.TokenBlacklist", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.User", "BlacklistedByUser")
                        .WithMany()
                        .HasForeignKey("BlacklistedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlacklistedByUser");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.User", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId");

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.UserGroupMembership", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.UserRole", b =>
                {
                    b.HasOne("EnterpriseIDS.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnterpriseIDS.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Group", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Members");

                    b.Navigation("RoleMappings");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.JwtToken", b =>
                {
                    b.Navigation("ChildTokens");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Role", b =>
                {
                    b.Navigation("GroupMappings");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.Tenant", b =>
                {
                    b.Navigation("ChildTenants");

                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("EnterpriseIDS.Core.Entities.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("GroupMemberships");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
